# Generated by Django 4.2.29 on 2026-03-26 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_number', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, null=True)),
                ('pair', models.CharField(max_length=20)),
                ('session', models.CharField(blank=True, choices=[('london_open', 'London open'), ('london_mid', 'London mid'), ('ny_open', 'NY open'), ('ny_mid', 'NY mid'), ('overlap', 'London/NY overlap'), ('asian', 'Asian'), ('off', 'Off-session')], max_length=20)),
                ('m15_bias', models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short'), ('ranging', 'Ranging')], max_length=10)),
                ('entry_tf', models.CharField(blank=True, choices=[('m15', 'M15 direct'), ('m5', 'M5'), ('m3', 'M3'), ('m1', 'M1')], max_length=5)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A-grade'), ('B', 'B-grade'), ('SKIP', 'Skip / Invalid')], max_length=5)),
                ('grade_reason', models.TextField(blank=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('sl_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('planned_rr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('be', 'Break-even'), ('not_taken', 'Not taken')], max_length=10)),
                ('actual_r', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=200)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/%Y/%m/')),
                ('setup_notes', models.TextField(blank=True)),
                ('improvement_notes', models.TextField(blank=True)),
                ('psych_tags', models.JSONField(blank=True, default=list)),
                ('psych_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-setup_number'],
                'unique_together': {('user', 'setup_number')},
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('entry_refinement', 'Entry refinement (M5/M3/M1)'), ('session_pattern', 'Session pattern'), ('stopout_condition', 'Stop-out condition'), ('breakeven_rule', 'Break-even rule'), ('higher_level', 'Moving to higher level'), ('general', 'General observation')], default='general', max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='journal.setup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
